# Fixit configuration

keyword: ['fixme', 'todo', 'to-do', 'fix-me']
pattern: '\/\/\s*@?(%keyword%):?\s+(.+)'
titles:  ['Line', 'Type', 'Comment']

include: ~
exclude: ~
include_file: ~
exclude_file: ~

output_type: table